name: Deploy React App to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: ecr-login
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 203918869233.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY_NAME }} .

    - name: Tag Docker Image
      run: |
        docker tag ${{ secrets.ECR_REPOSITORY_NAME }}:latest 203918869233.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest

    - name: Push Docker Image to Amazon ECR
      run: |
        docker push 203918869233.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0

      with:
        host: 44.212.24.103
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22 #${{ secrets.PORT }}
        script: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 203918869233.dkr.ecr.us-east-1.amazonaws.com
          docker stop my-container || true
          docker rm my-container || true
          docker pull 203918869233.dkr.ecr.us-east-1.amazonaws.com/gitaction-repo:latest
          docker run -d --name my-container -p 3000:3000 203918869233.dkr.ecr.us-east-1.amazonaws.com/gitaction-repo:latest
